module.exports.product1 = ['Hand-painted pottery',
'Crochet blankets',
'Knitted scarves',
'Wooden picture frames',
'Quilted wall hangings',
'Beaded jewelry',
'Hand-sewn purses',
'Decorative candles',
'Embroidered linens',
'Hand-carved wooden bowls',
'Woven baskets',
'Hand-stamped stationery',
'Soap made with natural ingredients',
'Hand-painted glassware',
'Knitted hats',
'Decorative wreaths',
'Hand-thrown pottery',
'Hand-knitted socks',
'Felted wool items',
'Decorative pillows']

module.exports.product2 = [
'Hand-printed textiles',
'Embroidered patches',
'Hand-sewn stuffed animals',
'Dried floral arrangements',
'Wooden toys',
'Macramé plant hangers',
'Hand-dipped incense',
'Knitted sweaters',
'Painted wooden signs',
'Hand-sewn clothing',
'Hand-spun yarn',
'Knitted blankets',
'Decorative paper goods',
'Hand-crafted soaps',
'Hand-painted furniture',
'Hand-embroidered table runners',
'Knitted baby items',
'Hand-stamped jewelry'
] 

module.exports.product3 = [
'Decorative bookends',
'Hand-dyed silk scarves',
'Knitted shawls',
'Hand-sewn tote bags',
'Wooden cutting boards',
'Hand-painted ceramics',
'Decorative wall art',
'Hand-sewn curtains',
'Knitted stuffed toys',
'Wooden kitchen utensils',
'Hand-painted canvas shoes',
'Hand-stamped leather goods',
'Decorative magnets',
'Hand-knitted pouches',
'Wooden door hangers',
'Hand-sewn aprons',
'Decorative birdhouses',
'Knitted neck warmers',
'Hand-painted glass ornaments',
'Hand-stamped coasters',
'Decorative picture frames',
'Hand-crocheted blankets.'
]