module.exports.title = [
'KnitWits',
'Pottery Pals',
'Beaded Bliss',
'Crafty Canvas',
'Sew Sweet',
'Scrapbook Central',
'Wooden Wonders',
'Quilting Queen',
'Yarn Yarns',
'Mosaic Magic',
'Crochet Craze',
'Stitching Station',
'Artistic Adventures',
'Embroidery Express',
'Weaving World',
'Paint Palette',
'Scrapbookers’ Spot',
'Knick-Knack Nook',
'Threaded Treasures',
'Découpage Den',
]